### PR TITLE
Fixes #674 -- scratch for writing reporter files

### LINKED ISSUE #674: Textfile reporter writing to arbitrary locations
When the python client is executing a section, if the section fails for some reason the results file will be written to the current working directory - i.e. wherever the failure occurred.
Additionally, it seems that when there is no tests to run it is just being written to $HOME.

### PR DESCRIPTION
**Pull request by ribab**
TextFile plugin and JunitXML plugin now write to the pre-defined scratch directory

### CODE REVIEW

**Comment by ribab** [comment]
TravisCI fails because this changes the location that files are being reported to.

I need to change the travisci test as a part of this pull request so that way travisci will pass.

File: tests/bat/default_check_profile.sh [hunk 1]
```diff
@@ -10,5 +10,5 @@ logfile=${LOGFILE:? LOGFILE not set}
 # Check that the logfile has correct version string
 # Remove the line in the logfile that was used for passing in KERNEL_RELEASE environment variable
 # The logfile will live at the top of the <scratchdir>/<testname> directory structure
-cat ../../$logfile | grep -v KERNEL_RELEASE | grep $kernel_release
+cat ../$logfile | grep -v KERNEL_RELEASE | grep $kernel_release
```
Comment (jsquyres) [inline tests/bat/default_check_profile.sh]: Just curious -- if `$logfile` is being set by the user, why isn't it set to the correct logfilename such that you have to prefix it with `..`?

(after thinking about this for a minute) ...oh, is `$logfile` a basename?  If so, it might be easier / more robust to just set `$logfile` to an absolute pathname, and avoid exactly this kind of issue in the future.

Just a thought.

File: pylib/Stages/Reporter/JunitXML.py [hunk 2]
```diff
@@ -57,7 +57,7 @@ def execute(self, log, keyvals, testDef):
         cmds = {}
         testDef.parseOptions(log, self.options, keyvals, cmds)
         if cmds['filename'] is not None:
-            self.fh = open(cmds['filename'], 'w')
+            self.fh = open(os.path.join(cmds['scratch'],cmds['filename']), 'w')
```
Comment (PeterGottesman) [inline pylib/Stages/Reporter/JunitXML.py]: Would it be worth it to check if `cmds['filename']` is an absolute path before appending it to the scratch directory?

Comment (ribab) [reply pylib/Stages/Reporter/JunitXML.py]: I am assuming that cmds['scratch'] is already an absolute path when that is set by TestDef

File: tests/bat/default_check_profile.sh (hunk 1 above)
Comment (ribab) [reply tests/bat/default_check_profile.sh]: That sounds good

File: pylib/Stages/Reporter/JunitXML.py (hunk 2 above)
Comment (PeterGottesman) [reply pylib/Stages/Reporter/JunitXML.py]: Right, but if the user sets the reporter's file to `/home/user/not/in/scratch/junit.xml` and scratch is at `/home/user/scratch`, this will output it to `/home/user/scratch/home/user/not/in/scratch/junit.xml`. So I am asking if it is worth it to check  if the filename is already an absolute path.

If it should _just_ be a filename and not a path to a file then it should be fine left as-is IMO. Just wanted your input there.

Comment (ribab) [reply pylib/Stages/Reporter/JunitXML.py]: I see

I will add a check for abs path before joining the paths then
